### PR TITLE
Louisiana-Jail-Scraper

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
Thanks for the submission! Since we haven't had a submission since going full-time, here's how it's gonna go: I'll check this for "can someone who barely knows anything run the scraper?" and @thejqs will check for "is anything weird or dangerous?". We'll get back to you ASAP.

**Review by josh-chamberlain — CHANGES_REQUESTED** [review]
1. I got this to run with a virtual environment, which Scrapy recommends. Could you add that to the readme, if it makes sense to you?

```
virtualenv scraper-la-jails
source scraper-la-jails/bin/activate
pip install scrapy
```

2. Where did you see the requirement about adding an ETL and schema.json? That's a bit out of date. Not a problem, but not really necessary either.

**Comment by ayyubibrahimi** [comment]
1. Added
2. My bad. I was reviewing other scrapers. I failed to check which requirements were most up-to-date. 

Lmk if there is anything else

**Review by josh-chamberlain — DISMISSED** [review]

**Comment by josh-chamberlain** [comment]
@ayyubibrahimi no worries, our contributing guide was really out of date and there's some old infrastructure around. We'll get this merged soon 👍

**Review by thejqs — APPROVED** [review]
ASAP took longer than anticipated, but thank you for this. A welcome addition.

**Pull request merged**
